%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosFileTransfer_File
%% Source: /net/isildur/ldisk/daily_build/r16b03_prebuild_opu_o.2013-12-09_20/otp_src_R16B03/lib/cosFileTransfer/src/CosFileTransfer.idl
%% IC vsn: 4.3.4
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSFILETRANSFER_FILE_HRL).
-define(COSFILETRANSFER_FILE_HRL, true).




-endif.


