CC	= gcc
SRC	= src/
CFLAGS  = -O
LIBS	= -lm  -L/usr/local/ssl/lib -lssl -lcrypto  -lresolv 
INCLUDE = -I./src/ -I. -I/usr/local/ssl/include
OBJS	= src/psybnc.o src/match.o src/p_client.o src/p_crypt.o src/p_dcc.o src/p_hash.o src/p_idea.o src/p_inifunc.o src/p_link.o src/p_log.o src/p_memory.o src/p_network.o src/p_parse.o src/p_peer.o src/p_server.o src/p_socket.o src/p_string.o src/p_sysmsg.o src/p_userfile.o src/p_uchannel.o src/p_script.o src/p_topology.o src/p_intnet.o src/p_blowfish.o src/p_translate.o src/p_coredns.o src/snprintf.o 
DEFINE	= -DHAVE_CONFIG -DBIGENDIAN -DIPV6  -DNOSYSTIME -DHAVE_SSL 
TARGET	= psybnc

all:	$(OBJS)
	$(CC) -o $(TARGET) $(CFLAGS) $(OBJS) $(LIBS)
	@strip $(TARGET)
	@echo "*** GENERATING SSL-KEYS FROM CERTIFICATE **"
	@echo "* You will be prompted for Cert-Contents  *"
	@echo "*  This Infos will be used only for SSL   *"
	@echo "* Alter the informations to your values   *"
	@echo "* for the sake of correct Cert-Checking   *"
	@echo "*******************************************"
	@echo "Generating certificate request .. "
	@/bin/openssl req -new -config src/ssl.cnf -out key/psybnc.req.pem \
      	-keyout key/psybnc.key.pem -nodes
	@echo "Generating self-signed certificate .. "
	@/bin/openssl req -x509 -days 365 -in key/psybnc.req.pem \
       	-key key/psybnc.key.pem -out key/psybnc.cert.pem
	@echo "Generating fingerprint .."
	@/bin/openssl x509 -subject -dates -fingerprint -noout \
		-in key/psybnc.cert.pem
	@echo psyBNC2.3.2-7-Linux ready. Please read the README before you run psybnc.

include ./targets.mak
