%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosNaming
%% Source: /net/isildur/ldisk/daily_build/r16b03_prebuild_opu_o.2013-12-09_20/otp_src_R16B03/lib/orber/COSS/CosNaming/cos_naming.idl
%% IC vsn: 4.3.4
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSNAMING_HRL).
-define(COSNAMING_HRL, true).


-record('CosNaming_NameComponent', {id, kind}).
-record('CosNaming_Binding', {binding_name, binding_type}).


-endif.


