%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: ETraP_Server
%% Source: /net/isildur/ldisk/daily_build/r16b03_prebuild_opu_o.2013-12-09_20/otp_src_R16B03/lib/cosTransactions/src/CosTransactions.idl
%% IC vsn: 4.3.4
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(ETRAP_SERVER_HRL).
-define(ETRAP_SERVER_HRL, true).




-endif.


